### ISSUE TITLE
Additional horizontal space between two bbrenv environments

### ISSUE THREAD

**Issue by arnomi** [arnomi/cryptocode#1]
See question on [StackExchange](https://tex.stackexchange.com/questions/538466/cryptocode-remove-annoying-margins-around-figures).

The problem seems to be the additional empty node inserted to allow xshifts. Regrettably there is no simple workaround. Within the sty file it can be fixed via

```
\ifthenelse{\equal{\bbrboxxshift}{0cm}}{}{
\node[inner sep=0pt, outer sep=0pt] at (\@bb@lastbox-tmpouter) {}; %this empty node seems needed to get the xyshift right.
}
```

**Comment by arnomi** [comment]
Fixed on develop. Will be part of v0.41

**Comment by tobiasBora** [comment]
Thanks a lot!
