### ISSUE TITLE
Space after \adv

### ISSUE THREAD

**Issue by theova** [arnomi/cryptocode#7]
Hi

Thanks for the nice package!

I have found, that the whitespace after `\adv` is not preserved in text mode:

Minimal Working Example:
```latex
\documentclass{article}
\usepackage[adversary]{cryptocode}
\begin{document}
This is an adversary \adv against whitespace.

But \adv~ should be like this.
\end{document}
```

which produces the following output:
![mwe](https://user-images.githubusercontent.com/32018176/117954484-58c72d00-b317-11eb-8ee7-d167128a37f2.png)

It would be very nice if that could be fixed :-)

**Comment by arnomi** [comment]
The easiest I can think of would be to use the xspace package and redefine `pcadvstyle`.

```
\documentclass{article}

\usepackage{xspace}
\usepackage[adversary]{cryptocode}

\renewcommand{\pcadvstyle}[1]{\ensuremath{\mathcal{#1}}\xspace}

\begin{document}

Adversary \adv now comes with spaces

\end{document}
```

**Comment by theova** [comment]
Nice, that works as expected (also there is no additional space in math mode). Thank you!
