### ISSUE TITLE
use of etex package

### ISSUE THREAD

**Issue by davidcarlisle** [arnomi/cryptocode#9]
Hi,

etex package hasn't done anything very useful since latex adopted an extended e-etex allocation scheme back in 2015. If the classical registers have aready been used up then etex.sty does nothing at all and gives a warning that worries some

https://tex.stackexchange.com/questions/605616/how-to-remove-the-etex-warning-when-using-cryptocode-with-the-llncs-document-cla

Could you consider dropping the package

**Comment by arnomi** [comment]
Hi David, 

thanks for the pointer. I'll look into it.

**Comment by arnomi** [comment]
Removed dependency on etex with version 0.44
